### ISSUE TITLE
Minimal debug info available for plugin

### ISSUE THREAD

**Issue by tdorsey** [jenkinsci/wix-plugin#6]
Jenkins 1.620, Wix 3.9, Wix plugin 1.11.

Using wix to build our installer. I'm not sure I have the configuration correct, but the plugin provides minimal debugging information. Building the .wixproj with an msbuild step correctly generates the msi. Output from the jenkins buildlog: 

https://gist.github.com/tdorsey/61ca3f35c6ff331823aa

In short, the plugin prints environment variables, then marks the build as failed. How can I see the error in more detail?

**Comment by rollinhand** [comment]
I had a look at your posted logfile and the lines
**[wix] VarName: BUILD_TAG; Value: jenkins-Vesta PMM-43
[wix] Conversion = 'P'**
look faulty. Can you please tell me what is the content of your Variable BUILD_TAG?!

Wix plugin has no debug line starting with _Conversion = 'P'_. My first intention is that your environment variable BUILD_TAG uses newlines.

You have Debugging enabled. So if there is no more output it seems that the plugin is crashed and you should have a look at the Jenkins logging.

Let me know if you need further assistance.

**Comment by tdorsey** [comment]
The git system log is less helpful, although there is a warning. 

The BUILD_TAG variable is controlled and set by Jenkins, along with some others listed at https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables. We are not using it, although our project might start with a P, as it is either VestaPMM or PMM, depending. It's helpful to know that The conversion tag is not wix related.

Jul 15, 2015 10:24:47 AM WARNING hudson.model.Run getEnvironment
deprecated call to Run.getEnvironment
	at de.berg.systeme.jenkins.wix.Toolset.<init>(Toolset.java:60)
Jul 15, 2015 10:24:48 AM INFO hudson.model.Run execute
Vesta PMM #42 main build action completed: FAILURE

**Comment by rollinhand** [comment]
So we can only try to narrow the problem. There are two ways to find out if the problem is related to environment variables:

1. If you do not need variables for your Wix project disable the automatic addition in global configuration options for the plugin by setting "Add environment variables as parameters" to disabled  -OR-
2. If it is only a problem with the environment variable BUILD_TAG try to add it in the global configuration option to the list of rejected environment variables.

Meanwhile I will try to write a test script if the seen error can occur by adding variables containing a newline or something else.

**Comment by tdorsey** [comment]
Results with environment variables disabled:

Time Elapsed 00:00:00.09
[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 1
[wix] Initializing tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] Compiler found.
[wix] Linker found.
[wix] Starting compile process...
[wix] isValid: C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\PMMInstall.wxs
[wix] isValid: true
[wix] adding source file: C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\PMMInstall.wxs
[wix] Executing command: "C:\Program Files\WiX Toolset v3.9\bin\candle.exe" -arch x86 -ext WixBalExtension -ext WixUIExtension -ext WixUtilExtension -ext WixNetFxExtension -nologo -out "C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\PMMInstall.wixobj" "C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\PMMInstall.wxs"
[Vesta PMM] $ "C:\Program Files\WiX Toolset v3.9\bin\candle.exe" -arch x86 -ext WixBalExtension -ext WixUIExtension -ext WixUtilExtension -ext WixNetFxExtension -nologo -out "C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\PMMInstall.wixobj" "C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\PMMInstall.wxs"
PMMInstall.wxs
C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\PMMInstall.wxs(29) : error CNDL0150 : Undefined preprocessor variable **'$(var.Resources)'**.
[wix] Compiling failed.
[wix] Compiling failed.
Build step 'WIX Toolset' changed build result to FAILURE
Finished: FAILURE

Results of option 2, since we are using build variables elsewhere.

"C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\VestaPMMInstaller.wixproj" (default target) (1) ->
(AddSolutionDefineConstants target) -> 
  C:\Program Files\MSBuild\Microsoft\WiX\v3.x\wix2010.targets(1236,5): warning : Solution properties are only available during IDE builds or when building the solution file from the command line. To turn off this warning set <DefineSolutionProperties>false</DefineSolutionProperties> in your .wixproj file. [C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMInstaller\VestaPMMInstaller.wixproj]

    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.11
[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 1
[wix] Initializing tools...
[wix] VarName: ALLUSERSPROFILE; Value: C:\ProgramData
[wix] VarName: APPDATA; Value: C:\Windows\system32\config\systemprofile\AppData\Roaming
[wix] VarName: BASE; Value: C:\Program Files\Jenkins
[wix] VarName: BUILD_DISPLAY_NAME; Value: #45
[wix] VarName: BUILD_ID; Value: 45
[wix] VarName: BUILD_NUMBER; Value: 45
[wix] BUILD_TAG: is marked as ignorable variable.
[wix] Rejected Environment variable: BUILD_TAG
[wix] Conversion = 'P'
Build step 'WIX Toolset' changed build result to FAILURE
Build step 'WIX Toolset' marked build as failure
Finished: FAILURE

We are intending to use the build variables to set some preprocessor directives in the .wixproj (you can see one causing the failure bolded above). Coud this be causing the issue?

**Comment by rollinhand** [comment]
Can you find out what the next environment variable would come up after BUILD_TAG or what preprocessor directives you have set? 

*Conversion = 'P'* _could_ be the message text of an exception which is internally thrown. I could add some advanced logging for caught exceptions and provide you a pre-version as downloadable hpi if that would help you. 

It must be a runtime exception while checking environment variables and I would like to find out where it occurs.

**Comment by tdorsey** [comment]
It appears from the logs that BUILD_TAG is the last env variable (although this is coming from what your plugin is logging). It did have a value of 'jenkins-Vesta PMM-44'. Is it possible that the whitespace in the build tag is causing an issue? 

If you have a custom hpi I'd be happy to try it.

**Comment by rollinhand** [comment]
That is only half of the truth. Before the plugin logs the variable information it has done some checks on it.

I will post a link to custom hpi tomorrow.

**Comment by rollinhand** [comment]
A pre-build of version 1.12 is available here:
https://dl.dropboxusercontent.com/u/105849591/wix.hpi
https://dl.dropboxusercontent.com/u/105849591/wix.jar

There is an advanced logging on all caught exceptions and the output on which variables the plugin is working on comes earlier - before the internal tests are done. Please test and send me some feedback. Thank you.

**Comment by tdorsey** [comment]
Looks like the debug logger is choking on print formats.

Time Elapsed 00:00:00.28
[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 1
[wix] Initializing tools...
[wix] VarName: ALLUSERSPROFILE; Value: C:\ProgramData
[wix] VarName: APPDATA; Value: C:\Windows\system32\config\systemprofile\AppData\Roaming
[wix] VarName: BASE; Value: C:\Program Files\Jenkins
[wix] VarName: BUILD_DISPLAY_NAME; Value: #51
[wix] VarName: BUILD_ID; Value: 51
[wix] VarName: BUILD_NUMBER; Value: 51
[wix] VarName: BUILD_TAG; Value: jenkins-Vesta PMM-51
[wix] Exception: Conversion = 'P'
[wix] SEVERE: Conversion = 'P'
[wix] Stacktrace follows:
java.util.UnknownFormatConversionException: Conversion = 'P'
	at java.util.Formatter$FormatSpecifier.conversion(Unknown Source)
	at java.util.Formatter$FormatSpecifier.<init>(Unknown Source)
	at java.util.Formatter.parse(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.io.PrintStream.format(Unknown Source)
	at java.io.PrintStream.printf(Unknown Source)
	**at de.berg.systeme.jenkins.wix.ToolsetLogger.debug(ToolsetLogger.java:119)**
	at de.berg.systeme.jenkins.wix.ToolsetLogger.debug(ToolsetLogger.java:106)
	at de.berg.systeme.jenkins.wix.WixCommand.parseSettings(WixCommand.java:148)
	at de.berg.systeme.jenkins.wix.WixCommand.<init>(WixCommand.java:102)
	at de.berg.systeme.jenkins.wix.Candle.<init>(Candle.java:56)
	at de.berg.systeme.jenkins.wix.Toolset.<init>(Toolset.java:62)
	at de.berg.systeme.jenkins.wix.WixToolsetBuilder.perform(WixToolsetBuilder.java:161)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Build step 'WIX Toolset' changed build result to FAILURE
Build step 'WIX Toolset' marked build as failure
Finished: FAILURE

**Comment by rollinhand** [comment]
Currently I cannot tell exactly what's going wrong. Exception comes from here:

public void debug(String format, Object...args) {
        if (debugEnabled) {
            check();
            String line = String.format(format, args);
            checkForErrors(line);
            *stream.printf("[wix] " + line);*
            stream.println();
            stream.flush();
        }
    }

But the output line with debug information is a simple string. The line marked bold is 119. Very interesting... Do you have environment variables or values of environment variables containing a % inside?

**Comment by tdorsey** [comment]
No special characters beyond anything you'd find in a windows path, and even those are being set by Jenkins. 




Where is the value of the format parameter being set from? "P" doesn't match any format string I'm aware of.

**Comment by rollinhand** [comment]
My suggestion was correct. If a String contains an extra %, Logger fails with the above seen exception. Icould verify this with a Unit-Test and fixed it.

You find a new pre build here:
https://dl.dropboxusercontent.com/u/105849591/wix.hpi
https://dl.dropboxusercontent.com/u/105849591/wix.jar

Please let me know if its working now.

**Comment by tdorsey** [comment]
That issue is resolved, but it looks like something has an issue with the filepath now

wix] VarName: APPDATA; Value: C:\Windows\system32\config\systemprofile\AppData\Roaming
[wix] VarName: BASE; Value: C:\Program Files\Jenkins
[wix] VarName: BUILD_DISPLAY_NAME; Value: #52
[wix] VarName: BUILD_ID; Value: 52
[wix] VarName: BUILD_NUMBER; Value: 52
[wix] VarName: BUILD_TAG; Value: jenkins-Vesta PMM-52
[wix] VarName: BUILD_URL; Value: http://localhost:8080/job/Vesta%20PMM/52/
[wix] VarName: CLASSPATH; Value: 
[wix] VarName: CommonProgramFiles; Value: C:\Program Files\Common Files
[wix] CommonProgramFiles: is marked as ignorable variable.
[wix] Rejected Environment variable: CommonProgramFiles
[wix] VarName: COMPUTERNAME; Value: IE10WIN7
[wix] VarName: ComSpec; Value: C:\Windows\system32\cmd.exe
[wix] VarName: Configuration; Value: Release
[wix] VarName: EXECUTOR_NUMBER; Value: 1
[wix] VarName: FP_NO_HOST_CHECK; Value: NO
[wix] VarName: HUDSON_HOME; Value: C:\Program Files\Jenkins
[wix] VarName: HUDSON_SERVER_COOKIE; Value: 8d79511d9b9fc923
[wix] VarName: HUDSON_URL; Value: http://localhost:8080/
[wix] VarName: JENKINS_HOME; Value: C:\Program Files\Jenkins
[wix] VarName: JENKINS_SERVER_COOKIE; Value: 8d79511d9b9fc923
[wix] VarName: JENKINS_URL; Value: http://localhost:8080/
[wix] VarName: JOB_NAME; Value: Vesta PMM
[wix] VarName: JOB_URL; Value: http://localhost:8080/job/Vesta%20PMM/
[wix] VarName: Lite; Value: false
[wix] VarName: LOCALAPPDATA; Value: C:\Windows\system32\config\systemprofile\AppData\Local
[wix] VarName: NODE_LABELS; Value: master
[wix] VarName: NODE_NAME; Value: master
[wix] VarName: NUMBER_OF_PROCESSORS; Value: 1
[wix] VarName: OS; Value: Windows_NT
[wix] VarName: Path; Value: C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files\Microsoft Windows Performance Toolkit\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\WiX Toolset v3.9\bin;
[wix] Path: is marked as ignorable variable.
[wix] Rejected Environment variable: Path
[wix] VarName: PATHEXT; Value: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
[wix] VarName: PROCESSOR_ARCHITECTURE; Value: x86
[wix] VarName: PROCESSOR_IDENTIFIER; Value: x86 Family 6 Model 42 Stepping 7, GenuineIntel
[wix] VarName: PROCESSOR_LEVEL; Value: 6
[wix] VarName: PROCESSOR_REVISION; Value: 2a07
[wix] VarName: ProgramData; Value: C:\ProgramData
[wix] VarName: ProgramFiles; Value: C:\Program Files
[wix] VarName: PSModulePath; Value: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
[wix] VarName: PUBLIC; Value: C:\Users\Public
[wix] VarName: SERVICE_ID; Value: jenkins
[wix] VarName: SVN_REVISION; Value: 510
[wix] VarName: SVN_REVISION_1; Value: 510
[wix] VarName: SVN_URL; Value: http://vestapartners.repositoryhosting.com/svn/vestapartners_vestapmm/VestaPMM/branches/jenkins_ci
[wix] VarName: SVN_URL_1; Value: http://vestapartners.repositoryhosting.com/svn/vestapartners_vestapmm/VestaPMM/branches/jenkins_ci
[wix] VarName: SystemDrive; Value: C:
[wix] VarName: SystemRoot; Value: C:\Windows
[wix] VarName: TEMP; Value: C:\Windows\TEMP
[wix] VarName: TMP; Value: C:\Windows\TEMP
[wix] VarName: USERDOMAIN; Value: WORKGROUP
[wix] VarName: USERNAME; Value: IE10WIN7$
[wix] VarName: USERPROFILE; Value: C:\Windows\system32\config\systemprofile
[wix] VarName: VS100COMNTOOLS; Value: C:\Program Files\Microsoft Visual Studio 10.0\Common7\Tools\
[wix] VarName: windir; Value: C:\Windows
[wix] VarName: WINSW_EXECUTABLE; Value: C:\Program Files\Jenkins\jenkins.exe
[wix] VarName: WIX; Value: C:\Program Files\WiX Toolset v3.9\
[wix] VarName: WORKSPACE; Value: C:\Program Files\Jenkins\workspace\Vesta PMM
[wix] VarName: ALLUSERSPROFILE; Value: C:\ProgramData
[wix] VarName: APPDATA; Value: C:\Windows\system32\config\systemprofile\AppData\Roaming
[wix] VarName: BASE; Value: C:\Program Files\Jenkins
[wix] VarName: BUILD_DISPLAY_NAME; Value: #52
[wix] VarName: BUILD_ID; Value: 52
[wix] VarName: BUILD_NUMBER; Value: 52
[wix] VarName: BUILD_TAG; Value: jenkins-Vesta PMM-52
[wix] VarName: BUILD_URL; Value: http://localhost:8080/job/Vesta%20PMM/52/
[wix] VarName: CLASSPATH; Value: 
[wix] VarName: CommonProgramFiles; Value: C:\Program Files\Common Files
[wix] CommonProgramFiles: is marked as ignorable variable.
[wix] Rejected Environment variable: CommonProgramFiles
[wix] VarName: COMPUTERNAME; Value: IE10WIN7
[wix] VarName: ComSpec; Value: C:\Windows\system32\cmd.exe
[wix] VarName: Configuration; Value: Release
[wix] VarName: EXECUTOR_NUMBER; Value: 1
[wix] VarName: FP_NO_HOST_CHECK; Value: NO
[wix] VarName: HUDSON_HOME; Value: C:\Program Files\Jenkins
[wix] VarName: HUDSON_SERVER_COOKIE; Value: 8d79511d9b9fc923
[wix] VarName: HUDSON_URL; Value: http://localhost:8080/
[wix] VarName: JENKINS_HOME; Value: C:\Program Files\Jenkins
[wix] VarName: JENKINS_SERVER_COOKIE; Value: 8d79511d9b9fc923
[wix] VarName: JENKINS_URL; Value: http://localhost:8080/
[wix] VarName: JOB_NAME; Value: Vesta PMM
[wix] VarName: JOB_URL; Value: http://localhost:8080/job/Vesta%20PMM/
[wix] VarName: Lite; Value: false
[wix] VarName: LOCALAPPDATA; Value: C:\Windows\system32\config\systemprofile\AppData\Local
[wix] VarName: NODE_LABELS; Value: master
[wix] VarName: NODE_NAME; Value: master
[wix] VarName: NUMBER_OF_PROCESSORS; Value: 1
[wix] VarName: OS; Value: Windows_NT
[wix] VarName: Path; Value: C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files\Microsoft Windows Performance Toolkit\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\WiX Toolset v3.9\bin;
[wix] Path: is marked as ignorable variable.
[wix] Rejected Environment variable: Path
[wix] VarName: PATHEXT; Value: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
[wix] VarName: PROCESSOR_ARCHITECTURE; Value: x86
[wix] VarName: PROCESSOR_IDENTIFIER; Value: x86 Family 6 Model 42 Stepping 7, GenuineIntel
[wix] VarName: PROCESSOR_LEVEL; Value: 6
[wix] VarName: PROCESSOR_REVISION; Value: 2a07
[wix] VarName: ProgramData; Value: C:\ProgramData
[wix] VarName: ProgramFiles; Value: C:\Program Files
[wix] VarName: PSModulePath; Value: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
[wix] VarName: PUBLIC; Value: C:\Users\Public
[wix] VarName: SERVICE_ID; Value: jenkins
[wix] VarName: SVN_REVISION; Value: 510
[wix] VarName: SVN_REVISION_1; Value: 510
[wix] VarName: SVN_URL; Value: http://vestapartners.repositoryhosting.com/svn/vestapartners_vestapmm/VestaPMM/branches/jenkins_ci
[wix] VarName: SVN_URL_1; Value: http://vestapartners.repositoryhosting.com/svn/vestapartners_vestapmm/VestaPMM/branches/jenkins_ci
[wix] VarName: SystemDrive; Value: C:
[wix] VarName: SystemRoot; Value: C:\Windows
[wix] VarName: TEMP; Value: C:\Windows\TEMP
[wix] VarName: TMP; Value: C:\Windows\TEMP
[wix] VarName: USERDOMAIN; Value: WORKGROUP
[wix] VarName: USERNAME; Value: IE10WIN7$
[wix] VarName: USERPROFILE; Value: C:\Windows\system32\config\systemprofile
[wix] VarName: VS100COMNTOOLS; Value: C:\Program Files\Microsoft Visual Studio 10.0\Common7\Tools\
[wix] VarName: windir; Value: C:\Windows
[wix] VarName: WINSW_EXECUTABLE; Value: C:\Program Files\Jenkins\jenkins.exe
[wix] VarName: WIX; Value: C:\Program Files\WiX Toolset v3.9\
[wix] VarName: WORKSPACE; Value: C:\Program Files\Jenkins\workspace\Vesta PMM
[wix] Compiler found.
[wix] Linker found.
[wix] Starting compile process...
[wix] adding source file: C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMBundler\PMMBundle.wxs
[wix] Executing command: "C:\Program Files\WiX Toolset v3.9\bin\candle.exe" -arch x86 -ext WixBalExtension -ext WixUIExtension -ext WixUtilExtension -ext WixNetFxExtension -dPROCESSOR_LEVEL=6 -dSVN_REVISION=510 -dConfiguration=Release -dFP_NO_HOST_CHECK=NO "-dHUDSON_HOME=C:\Program Files\Jenkins" -dSVN_URL=http://vestapartners.repositoryhosting.com/svn/vestapartners_vestapmm/VestaPMM/branches/jenkins_ci -dJOB_URL=http://localhost:8080/job/Vesta%20PMM/ -dALLUSERSPROFILE=C:\ProgramData -dPROCESSOR_ARCHITECTURE=x86 -dPSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\\ -dSystemDrive=C: "-dVS100COMNTOOLS=C:\Program Files\Microsoft Visual Studio 10.0\Common7\Tools\\" -dJENKINS_SERVER_COOKIE=8d79511d9b9fc923 -dSERVICE_ID=jenkins -dUSERNAME=IE10WIN7$ -dJENKINS_URL=http://localhost:8080/ "-dBUILD_TAG=jenkins-Vesta PMM-52" -dPATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC -dSVN_URL_1=http://vestapartners.repositoryhosting.com/svn/vestapartners_vestapmm/VestaPMM/branches/jenkins_ci "-dJENKINS_HOME=C:\Program Files\Jenkins" -dProgramData=C:\ProgramData -dNODE_NAME=master -dBUILD_DISPLAY_NAME=#52 "-dPROCESSOR_IDENTIFIER=x86 Family 6 Model 42 Stepping 7, GenuineIntel" "-dWINSW_EXECUTABLE=C:\Program Files\Jenkins\jenkins.exe" "-dProgramFiles=C:\Program Files" -dPUBLIC=C:\Users\Public -dSVN_REVISION_1=510 -dwindir=C:\Windows -dLOCALAPPDATA=C:\Windows\system32\config\systemprofile\AppData\Local -dUSERDOMAIN=WORKGROUP "-dWIX=C:\Program Files\WiX Toolset v3.9\\" -dBUILD_ID=52 "-dBASE=C:\Program Files\Jenkins" "-dJOB_NAME=Vesta PMM" -dAPPDATA=C:\Windows\system32\config\systemprofile\AppData\Roaming -dNODE_LABELS=master -dHUDSON_URL=http://localhost:8080/ "-dWORKSPACE=C:\Program Files\Jenkins\workspace\Vesta PMM" -dOS=Windows_NT -dCOMPUTERNAME=IE10WIN7 -dEXECUTOR_NUMBER=1 -dHUDSON_SERVER_COOKIE=8d79511d9b9fc923 -dLite=false -dPROCESSOR_REVISION=2a07 -dCLASSPATH= -dComSpec=C:\Windows\system32\cmd.exe -dBUILD_NUMBER=52 -dSystemRoot=C:\Windows -dTEMP=C:\Windows\TEMP -dBUILD_URL=http://localhost:8080/job/Vesta%20PMM/52/ -dUSERPROFILE=C:\Windows\system32\config\systemprofile -dTMP=C:\Windows\TEMP -dNUMBER_OF_PROCESSORS=1 -nologo -out "C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMBundler\PMMBundle.wixobj" "C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMBundler\PMMBundle.wxs"
[Vesta PMM] $ "C:\Program Files\WiX Toolset v3.9\bin\candle.exe" -arch x86 -ext WixBalExtension -ext WixUIExtension -ext WixUtilExtension -ext WixNetFxExtension ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** -nologo -out **"C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMBundler\PMMBundle.wixobj" "C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMBundler\PMMBundle.wxs"
candle.exe : error CNDL0001 : The given path's format is not supported.**

Exception Type: System.NotSupportedException

Stack Trace:
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Microsoft.Tools.WindowsInstallerXml.AppCommon.GetFiles(String searchPath, String fileType)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Candle.ParseCommandLine(String[] args)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Candle.Run(String[] args)
[wix] Compiling failed.
[wix] ToolsetException: Compiling failed.
[wix] SEVERE: Compiling failed.
[wix] Stacktrace follows:
de.berg.systeme.jenkins.wix.ToolsetException: Compiling failed.
	at de.berg.systeme.jenkins.wix.Toolset.compile(Toolset.java:173)
	at de.berg.systeme.jenkins.wix.Toolset.compile(Toolset.java:143)
	at de.berg.systeme.jenkins.wix.WixToolsetBuilder.perform(WixToolsetBuilder.java:165)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Build step 'WIX Toolset' changed build result to FAILURE
Finished: FAILURE

**Comment by rollinhand** [comment]
Are you sure you have write permissions on the directory C:\Program Files\Jenkins\workspace\Vesta PMM\VestaPMMBundler?

Candle.exe ist stating _System.Security.Permissions.FileIOPermission.AddPathList_ which could mean everything. You could try to execute the command constructed by the plugin directly in a command line on your Jenkins server and see what happens.

**Comment by tdorsey** [comment]
The jenkins service checked out successfully to that directory, so I'm assuming it can write, but that may not be the case. When the plugin calls candle and light, does it run under the same user?

My local user couldn't until I allowed full control, but then the build succeeded.

**Comment by rollinhand** [comment]
The plugin runs in the same user context as Jenkins. If the full command after _[wix] Executing command_ succeeded on command line, it should also work from Jenkins. There is no special magic because Jenkins spawns a process executing exactly the same command you did on command line.

**Comment by tdorsey** [comment]
Hm. Jenkins is running as a local service user with full control on that directory. My local user with full control can execute the command, but the service still fails.

**Comment by rollinhand** [comment]
One more thing you could try is to reject some variables like *SVN_URL* and *SVN_URL_1*. The others look like on our production system.
Otherwise I don't have a clue why it is failing...

**Comment by tdorsey** [comment]
One thing we noticed...some of the variables appear to have an extra trailing slash:

Compare:
[wix] VarName: VS100COMNTOOLS; Value: C:\Program Files\Microsoft Visual Studio 10.0\Common7\Tools\

dVS100COMNTOOLS=C:\Program Files\Microsoft Visual Studio 10.0\Common7\Tools\**\**"

**Comment by rollinhand** [comment]
Thanks for the hint. That might be the problem, that " gets escaped by the \ and also means that a bugfix introduced with 1.11 does not work properly. I will try to fix that too with 1.12.

**Comment by rollinhand** [comment]
Version 1.12 is officially released today.
