### ISSUE TITLE
Plugin warns 'not an MSI' when creating other filetypes (exe, etc)

### ISSUE THREAD

**Issue by tdorsey** [jenkinsci/wix-plugin#8]
Light.exe can be used to generate filetypes other than .msi, but a warning is displayed by the plugin when doing so.

![bug](https://cloud.githubusercontent.com/assets/1218404/8810521/8213e600-2fbd-11e5-96b4-b6eb2dd485e6.PNG)

Workaround: Ignore the warning message when specifying desired output extension

**Comment by rollinhand** [comment]
That is not right: You have to specifiy the ending correct for the "MSI package". 
If you add .msi there will be no warning. If you add .exe it will give you a hint, you have to activate BalExtension (Bootstrapper). In an upcoming release the plugin may then activate this extension automatically.

Other types of generated output files like MSM are not yet tested and therefore it is better to output a warning.

**Comment by tdorsey** [comment]
Msm was the case I was testing. In that case feel free to close.
