### ISSUE TITLE
wix jenkins plugin needs admin account?

### ISSUE THREAD

**Issue by frankySH** [jenkinsci/wix-plugin#9]
I run a simple wix jenkins plugin test. If the Jenkins runs under a admin account, everything is fine. I get errors if the Jenkins run under a user account with service rights:

light.exe : error LGHT0217 : Error executing ICE action 'ICE01'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".

So i call WIX direct as Windows batch with some parameters like "-sval -ext WixUtilExtension -sice:ICE20" . This works under the service rights user.

Is there a way to run the WIX Plugin without admin rights?

**Comment by rollinhand** [comment]
Can you please provide more information?

Which version of the plugin are you using?
Is Jenkins running as the same service account as used on the command line? The plugin uses the same account rights as Jenkins.
Please check if all necessary environment variables are set, when you start it under a service account and that there is no environment mismatch when starting on command line.

**Comment by frankySH** [comment]
Jenkins ver. 1.596.2
WIX Toolset Plugin: 1.12
OS: WIN 7
WIX Toolset: 3.9
The WIX Toolset Path (C:\Program Files (x86)\WiX Toolset v3.9\bin) is set in Jenkins and in PATH. 

I run Jenkins under a user account with service rights. There are 2 Jobs.
1. Job calls WIX via Win Batch. Here the call:
{code}
candle SampleFirst.wxs
"C:\Program Files (x86)\WiX Toolset v3.9\bin\light.exe" -sval -ext WixUtilExtension -sice:ICE20 SampleFirst.wixobj
{code}
2. Job calls build the same WIX file via WIX Toolset Plugin:
Source file "SampleFirst.wxs" for x86 without any options.

Only the first job was successful.

Thanks for your help.

**Comment by rollinhand** [comment]
Can you please provide a full log of the WiX plugin in Jenkins?
For me this looks like the Scripting engine of the WiX Toolset is missing something. That has nothing to do with the plugin running in Jenkins. The plugin is only a wrapper to encapsulate the commands executed mainly on command line.

Please see http://stackoverflow.com/questions/1064580/wix-3-0-throws-error-217-while-being-executed-by-continuous-integration.

**Comment by frankySH** [comment]
Here the log of the failed WIX plugin test:

{code}
Gestartet durch Benutzer anonymous
Baue in Arbeitsbereich C:\jenkins\jenkins1\data\jobs\15-wix-Test\workspace
[wix] Debug-Meldungen aktiviert: false
[wix] Auslesen der Umgebungsvariablen.
[wix] Gefundene Quelldateien: 1
[wix] Initialisiere Tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] Compiler gefunden.
[wix] Linker gefunden.
[wix] Kompiliere...
[wix] SampleFirst.wxs
[wix] Kompilieren erfolgreich.
[wix] Linke in Datei: C:\jenkins\jenkins1\data\jobs\15-wix-Test\workspace\setup.msi
[wix] light.exe : error LGHT0217 : Error executing ICE action 'ICE01'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
[wix] light.exe : error LGHT0217 : Error executing ICE action 'ICE02'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
[wix] light.exe : error LGHT0217 : Error executing ICE action 'ICE03'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
[wix] light.exe : error LGHT0217 : Error executing ICE action 'ICE04'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
[wix] light.exe : error LGHT0217 : Error executing ICE action 'ICE05'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
[wix] light.exe : error LGHT0217 : Error executing ICE action 'ICE06'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
[wix] light.exe : error LGHT0217 : Error executing ICE action 'ICE07'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
[wix] light.exe : error LGHT0216 : An unexpected Win32 exception with error code 0x643 occurred: Action - 'ICE09' Schwerwiegender Fehler bei der Installation
[wix] Linken fehlgeschlagen.
[wix] Linken fehlgeschlagen.
Build step 'WIX Toolset' changed build result to FAILURE
Finished: FAILURE
{code}

To the link:
I tried the last entry without success. My PATH variable is only 1 kB and 442 charackters long.

**Comment by rollinhand** [comment]
Sorry, I was not precise enough. If you active Debug-Logging on global Jenkins options for the WiX plugin you see the command which is called by Jenkins to compile and link the MSI package. 

Currently the flags -sval and -ICE are not supported because I am in lack of a real test set. You also find no parameters to influence the behavior of the consistency evaluator on the frontend. As I have seen, you executed light with -sval on the command line, which supresses all checks by ICE, so -sice:ICE20 has no effect.

What happens on command line if you simply execute "C:\Program Files (x86)\WiX Toolset v3.9\bin\light.exe" -ext WixUtilExtension SampleFirst.wixobj"?

If you like to see ICE supported by the plugin, I recommend to raise a Feature Request either on [JIRA of Jenkins](https://issues.jenkins-ci.org/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20'wix-plugin') or here on Github. If you could further provide a minimal example project using ICE, I can try to release a new version of the plugin as soon as possible.

What option in your WXS file tries to run all ICE-Tests?
